#ifndef PDS_BACKUP_SHARED_PROTOCOL
#define PDS_BACKUP_SHARED_PROTOCOL

#define PDSB_PROT_CURRVERSION "0001"
#define PDSB_PROT_HEADERLEN 40
#define PDSB_PROT_SEPCHAR ((char)0)

#define PDSB_PROT_USERCODE_OFFSET 8
#define PDSB_PROT_USERCODELEN 16

#define PDSB_PROT_BODYLEN_OFFSET 24

#endif